version: '3'

services:
  backend:
    env_file:
        "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "mustang_backend"
    ports:
      - "8080:8080"
  frontend:
    env_file: 
        "./frontend/.env"
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "mustang_frontend"
    ports:
      - "3000:3000"