name: Backend Build

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_J }}/${{ secrets.GCP_APP_NAME_BACKEND }}
          aws_access_key_id: ${{ secrets.aws_access_key_id}}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key}}
          mongodb_password: ${{ secrets.mongodb_password}}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID}}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN}}
          TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER}}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY}}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }} 
          REACT_APP_PEXELS_API_KEY: ${{ secrets.REACT_APP_PEXELS_API_KEY}}
          GCP_API_KEY: ${{ secrets.GCP_API_KEY }}
          

    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS_J }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      
    - name: 'Submit to cloud build'
      run: |
        cd backend
        gcloud builds submit --tag $IMAGE_NAME
    - name: 'Deploy to Cloud Run'
      run: gcloud run deploy ${{ secrets.GCP_APP_NAME_BACKEND }} --image $IMAGE_NAME --region us-central1 --platform managed --allow-unauthenticated
            --set-env-vars=aws_access_key_id=$aws_access_key_id
            --set-env-vars=aws_secret_access_key=$aws_secret_access_key
            --set-env-vars=mongodb_password=$mongodb_password
            --set-env-vars=TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
            --set-env-vars=TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
            --set-env-vars=TWILIO_PHONE_NUMBER=$TWILIO_PHONE_NUMBER
            --set-env-vars=STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
            --set-env-vars=REACT_APP_PEXELS_API_KEY=$REACT_APP_PEXELS_API_KEY
            --set-env-vars=GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
            --set-env-vars=GCP_API_KEY=$GCP_API_KEY
            

            
