
name: Cloud Run Deployment
on:
  push:
    branches:
      - main
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      
    - name: Getting Secrets
      env: 
        GCP_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'
        GCP_PROJECT : '${{ secrets.GCP_PROJECT }}'
        GCP_APPLICATION: '${{ secrets.GCP_APPLICATION }}'
        GCP_EMAIL: '${{ secrets.EMAIL }}' 
        GCP_TEST: 'Works?'
      run: |
        echo $GCP_TEST
        
        
    - name: Verification
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    # Build the Docker image
    - name: Build & Publish
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}
        gcloud config set run/region us-central1
      
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud run deploy ${{ secrets.GCP_APPLICATION }} --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }} \
        --platform managed \
        --allow-unauthenticated \
