name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get Secret Manager secrets
      uses: google-github-actions/get-secretmanager-secrets@v0.5.0

    
    - uses: actions/checkout@v3
    - name: Build the Docker image 
      run: docker build -t mustang .
      
    - name: Running Image
      run: docker run mustang
