name: Frontend Build

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_J }}/${{ secrets.GCP_APP_NAME_FRONTEND }}
          GOOGLE_MAPS_API_KEY: ${{secrets.GOOGLE_MAPS_API_KEY}}
          REACT_APP_STRIPE_PUBLISHABLE_KEY: ${{secrets.REACT_APP_STRIPE_PUBLISHABLE_KEY}}
          SERP_API_KEY: ${{secrets.SERP_API_KEY}}

    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS_J }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      
    - name: 'Submit to cloud build'
      run: |
        cd frontend
        gcloud builds submit --tag $IMAGE_NAME
    - name: 'Deploy to Cloud Run'
      run: gcloud run deploy ${{ secrets.GCP_APP_NAME_FRONTEND }} --image $IMAGE_NAME --region us-central1 --platform managed --allow-unauthenticated
            --set-env-vars=GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY
            --set-env-vars=REACT_APP_STRIPE_PUBLISHABLE_KEY=$REACT_APP_STRIPE_PUBLISHABLE_KEY
            --set-env-vars=SERP_API_KEY=$SERP_API_KEY

